name: geopulse
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  motion_tab_bar: ^2.0.4
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.4
  geolocator: ^13.0.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^18.0.0
  flutter_background_service_android: ^6.2.7
  intl: ^0.19.0
  permission_handler: ^10.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/main1.png"

flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
